/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { Clone, Float, Html, OrthographicCamera } from "@react-three/drei";
import { Hoverable } from "./Hoverable";
import { Bubble } from "./Bubble";
import { useState } from "react";
import { useSpring, config, animated } from "@react-spring/three";
import { useThree } from "@react-three/fiber";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/13EUVz6gvyRUF9ej/scene.spline"
  );

  const [showCoffee, setShowCoffee] = useState(false);
  const [showComputer, setShowComputer] = useState(false);
  const size = useThree((state) => state.size);
  const isMobile = size.width < 768;

  const { sceneRotationY } = useSpring({
    sceneRotationY: showComputer ? Math.PI * 0.93 : 0,
    config: config.slow
  });

  return (
    <>
      <color attach="background" args={["#d9d7f3"]} />

      <OrthographicCamera
        makeDefault={true}
        zoom={isMobile ? 0.5 : 1.11}
        far={500000}
        near={-500000}
        name="Camera 2"
        position={[135.06, 132.31, 988.56]}
        rotation={[-0.15, 0.03, 0]}
      />

      <animated.group
        {...props}
        rotation-y={sceneRotationY}
        position-x={isMobile ? 0 : 150}
        position-y={isMobile ? 150 : 0}
        dispose={null}
      >
        <group position={[2.5, 205.8, -62.46]}>
          <Html>
            <Bubble show={showCoffee}>Oh I want some coffee...</Bubble>
          </Html>
        </group>
        <group
          name="Group 14"
          position={[89.16, 217.94, -31.5]}
          rotation={[0.25, -0.53, 0.08]}
          scale={1.22}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials["Cylinder Material"]}
            castShadow
            receiveShadow
            position={[0.06, 5.4, 33.96]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            name="Cube 3"
            geometry={nodes["Cube 3"].geometry}
            material={materials["Cube 3 Material"]}
            castShadow
            receiveShadow
            position={[33.6, 1.21, 30.85]}
            rotation={[0, 1.4, 0]}
          />
          <mesh
            name="Cube 2"
            geometry={nodes["Cube 2"].geometry}
            material={materials["Cube 2 Material"]}
            castShadow
            receiveShadow
            position={[-33, 0.81, 30.81]}
            rotation={[-Math.PI, 1.4, -Math.PI]}
          />
          <mesh
            name="Torus 2"
            geometry={nodes["Torus 2"].geometry}
            material={materials["Torus 2 Material"]}
            castShadow
            receiveShadow
            position={[18.4, 0.83, 33.98]}
            rotation={[0, 0, -0.02]}
          />
          <mesh
            name="Torus"
            geometry={nodes.Torus.geometry}
            material={materials["Torus Material"]}
            castShadow
            receiveShadow
            position={[-17.94, 1.59, 33.98]}
            rotation={[0, 0, -0.02]}
          />
        </group>
        <mesh
          receiveShadow
          rotation={[-Math.PI * 0.5, 0, 0]}
          position={[0, -329, 0]}
        >
          <planeGeometry args={[2000, 2000]} />
          <shadowMaterial opacity={0.2} />
        </mesh>
        <group name="bg" position={[175.03, 5.04, -190.02]}>
          <group name="table" position={[-442.78, -245.69, 115.3]}>
            <group name="book1" position={[-46.78, 127.46, -60.44]}>
              <mesh
                name="Cube 31"
                geometry={nodes["Cube 31"].geometry}
                material={materials["Cube 31 Material"]}
                castShadow
                receiveShadow
                position={[-0.15, 0.04, 0.61]}
                rotation={[-0.05, 0.49, 1.61]}
                scale={[0.39, 0.78, 0.58]}
              />
              <mesh
                name="Cube 32"
                geometry={nodes["Cube 32"].geometry}
                material={materials["Cube 32 Material"]}
                castShadow
                receiveShadow
                position={[2.8, -6.42, 5.6]}
                rotation={[-0.05, 0.49, 1.61]}
                scale={[0.39, 0.78, 0.58]}
              />
            </group>
            <group name="book2" position={[-41.19, 105.95, -64.04]}>
              <mesh
                name="Cube 21"
                geometry={nodes["Cube 21"].geometry}
                material={materials["Cube 21 Material"]}
                castShadow
                receiveShadow
                position={[0.14, 0.01, 1]}
                rotation={[0, 0.74, Math.PI / 2]}
                scale={[0.59, 0.95, 0.8]}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials["Cube Material"]}
                castShadow
                receiveShadow
                position={[5.38, -9.87, 5.9]}
                rotation={[0, 0.74, Math.PI / 2]}
                scale={[0.59, 0.95, 0.8]}
              />
            </group>
            <group name="book 3" position={[-12.71, 101.21, 32.16]}>
              <mesh
                name="Cube 4"
                geometry={nodes["Cube 4"].geometry}
                material={materials["Cube 4 Material"]}
                castShadow
                receiveShadow
                position={[0.22, 0.21, 0.74]}
                rotation={[0, 1.29, 1.56]}
                scale={[0.39, 0.7, 0.58]}
              />
              <mesh
                name="Cube 41"
                geometry={nodes["Cube 41"].geometry}
                material={materials["Cube 41 Material"]}
                castShadow
                receiveShadow
                position={[5.63, -6.5, 1.6]}
                rotation={[0, 1.29, 1.56]}
                scale={[0.39, 0.7, 0.58]}
              />
            </group>
            <Hoverable
              onClick={() => {
                setShowComputer(false);
                setShowCoffee(!showCoffee);
              }}
            >
              <Clone object={nodes.coffee} />
            </Hoverable>
            <mesh
              name="Cube 42"
              geometry={nodes["Cube 42"].geometry}
              material={materials["Cube 42 Material"]}
              castShadow
              receiveShadow
              position={[-0.36, -8.7, 88.76]}
              rotation={[-0.17, -Math.PI / 2, 0]}
            />
            <mesh
              name="Cube 33"
              geometry={nodes["Cube 33"].geometry}
              material={materials["Cube 33 Material"]}
              castShadow
              receiveShadow
              position={[85.14, -8.7, 3.26]}
              rotation={[0, 0, 0.17]}
            />
            <mesh
              name="Cube 43"
              geometry={nodes["Cube 43"].geometry}
              material={materials["Cube 43 Material"]}
              castShadow
              receiveShadow
              position={[-0.36, -5.16, -82.24]}
              rotation={[0.17, -Math.PI / 2, 0]}
            />
            <mesh
              name="Cube 22"
              geometry={nodes["Cube 22"].geometry}
              material={materials["Cube 22 Material"]}
              castShadow
              receiveShadow
              position={[-85.86, -5.16, 3.26]}
              rotation={[0, 0, -0.17]}
            />
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials["Cylinder1 Material"]}
              castShadow
              receiveShadow
              position={[0, 81.85, 0]}
            />
          </group>
          <Float>
            <Clone object={nodes.FloatingArrow} />
          </Float>
          <Float>
            <Clone object={nodes.FloatingCross} />
          </Float>
          <Float>
            <Clone object={nodes.FloatingMagnif} />
          </Float>
          <Float>
            <Clone object={nodes.FloatingTorus} />
          </Float>
          <mesh
            name="groundCube"
            geometry={nodes.groundCube.geometry}
            material={materials["Ground shapes"]}
            castShadow
            receiveShadow
            position={[407.8, -280.54, -223.32]}
            rotation={[-Math.PI / 2, 0, 0.26]}
          />
          <mesh
            name="groundPyramid"
            geometry={nodes.groundPyramid.geometry}
            material={materials["groundPyramid Material"]}
            castShadow
            receiveShadow
            position={[-394.91, -275.6, 211.76]}
            rotation={[-0.06, -0.14, 0.91]}
          />
          <mesh
            name="groundSphere"
            geometry={nodes.groundSphere.geometry}
            material={materials["Ground shapes"]}
            castShadow
            receiveShadow
            position={[54.31, -290.76, -214.49]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group name="lamp" position={[205.45, 12.8, 57.19]}>
            <mesh
              name="Sphere 2"
              geometry={nodes["Sphere 2"].geometry}
              material={materials["Sphere 2 Material"]}
              castShadow
              receiveShadow
              position={[-62.28, 256.7, 49.13]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube 7"
              geometry={nodes["Cube 7"].geometry}
              material={materials["Cube 7 Material"]}
              castShadow
              receiveShadow
              position={[-51.78, 282.28, 41.49]}
              rotation={[0, 0.7, Math.PI / 3]}
            />
            <mesh
              name="Cube 6"
              geometry={nodes["Cube 6"].geometry}
              material={materials["Cube 6 Material"]}
              castShadow
              receiveShadow
              position={[47.95, -248.79, -37.78]}
              rotation={[0, 0.7, 0]}
            />
            <mesh
              name="Cylinder 2"
              geometry={nodes["Cylinder 2"].geometry}
              material={materials["Plastic blue"]}
              castShadow
              receiveShadow
              position={[49.13, -333.68, -36.39]}
              rotation={[0, 0.7, 0]}
            />
          </group>
          <group
            name="Group 7"
            position={[151.22, -181.47, 176.31]}
            scale={0.85}
          >
            <mesh
              name="Cube 12"
              geometry={nodes["Cube 12"].geometry}
              material={materials["Cube 12 Material"]}
              castShadow
              receiveShadow
              position={[2.69, -4.14, 10.5]}
              rotation={[2.94, 1.13, -2.96]}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes["Cylinder 21"].geometry}
              material={materials["Cylinder 21 Material"]}
              castShadow
              receiveShadow
              position={[-6.01, -88.9, 16.97]}
            />
            <mesh
              name="Cube 9"
              geometry={nodes["Cube 9"].geometry}
              material={materials["Plastic green"]}
              castShadow
              receiveShadow
              position={[-9.73, 111.05, 11.87]}
              rotation={[0, 0.99, 0]}
            />
            <mesh
              name="Cube 8"
              geometry={nodes["Cube 8"].geometry}
              material={materials["Cube 8 Material"]}
              castShadow
              receiveShadow
              position={[19.63, 80.03, 5.85]}
              rotation={[-0.33, -1.3, -0.3]}
            />
            <mesh
              name="Cube 10"
              geometry={nodes["Cube 10"].geometry}
              material={materials["Cube 10 Material"]}
              castShadow
              receiveShadow
              position={[12.32, 119.61, 29.02]}
              rotation={[-3.01, -0.73, -3.03]}
            />
            <mesh
              name="Cube 11"
              geometry={nodes["Cube 11"].geometry}
              material={materials["Cube 11 Material"]}
              castShadow
              receiveShadow
              position={[-27.62, -3.9, 28.51]}
              rotation={[-2.72, 1.12, 2.73]}
            />
            <mesh
              name="Cube 71"
              geometry={nodes["Cube 71"].geometry}
              material={materials["Cube 71 Material"]}
              castShadow
              receiveShadow
              position={[2.77, 52.94, -5.43]}
              rotation={[0, 0.26, 0]}
            />
            <mesh
              name="Cube 61"
              geometry={nodes["Cube 61"].geometry}
              material={materials["Cube 61 Material"]}
              castShadow
              receiveShadow
              position={[-5.26, -137.14, 16.39]}
            />
          </group>
          <Float>
            <Clone object={nodes.FloatingAtoms} />
          </Float>
        </group>
        <group
          name="body"
          position={[65.57, -56.59, 12.79]}
          rotation={[0, -Math.PI / 6, 0]}
        >
          <group name="Group 3" position={[-13.09, -119.48, -84.83]}>
            <mesh
              name="Cube 34"
              geometry={nodes["Cube 34"].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-42.8, -31.85, -48.45]}
              rotation={[0.17, -0.03, -0.17]}
            />
            <mesh
              name="Cube 35"
              geometry={nodes["Cube 35"].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[41.57, -32.53, -48.75]}
              rotation={[0.19, -0.09, 0.17]}
            />
            <mesh
              name="Cube 23"
              geometry={nodes["Cube 23"].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-43.1, -34.67, 48.83]}
              rotation={[-0.18, -0.03, -0.17]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[41.74, -34.51, 48.55]}
              rotation={[-0.16, -0.09, 0.17]}
            />
            <mesh
              name="Cylinder 3"
              geometry={nodes["Cylinder 3"].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-0.14, -68.35, 0.22]}
              scale={0.85}
            />
            <mesh
              name="Cylinder 22"
              geometry={nodes["Cylinder 22"].geometry}
              material={materials["Cylinder 22 Material"]}
              castShadow
              receiveShadow
              position={[-1.79, 84.88, 0.22]}
              scale={0.85}
            />
            <mesh
              name="Cylinder2"
              geometry={nodes.Cylinder2.geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-1.79, 93.36, 0.22]}
              scale={0.85}
            />
          </group>
          <Hoverable
            onClick={() => {
              setShowCoffee(false);
              setShowComputer(!showComputer);
            }}
          >
            <Clone object={nodes.computer} />
          </Hoverable>
          <group
            name="Group 5"
            position={[-29.31, -168.52, 15.44]}
            rotation={[0.87, 0, 0.26]}
            scale={[1.8, 1.76, 1.71]}
          >
            <mesh
              name="Torus 21"
              geometry={nodes["Torus 21"].geometry}
              material={materials["Torus 21 Material"]}
              castShadow
              receiveShadow
              position={[0.03, -7.05, 7.24]}
              rotation={[0, 0, -0.61]}
            />
            <mesh
              name="Torus1"
              geometry={nodes.Torus1.geometry}
              material={materials["Torus1 Material"]}
              castShadow
              receiveShadow
              position={[0, -5.6, 2.14]}
              rotation={[0, 0, -Math.PI / 4]}
            />
            <mesh
              name="Cube 44"
              geometry={nodes["Cube 44"].geometry}
              material={materials["Cube 44 Material"]}
              castShadow
              receiveShadow
              position={[0.03, -5.56, -27.01]}
              rotation={[Math.PI, 0, 0]}
              scale={0.9}
            />
            <mesh
              name="Cube 36"
              geometry={nodes["Cube 36"].geometry}
              material={materials["Sneakers white"]}
              castShadow
              receiveShadow
              position={[-0.5, -10.06, 16.62]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube 24"
              geometry={nodes["Cube 24"].geometry}
              material={materials["Sneakers blue"]}
              castShadow
              receiveShadow
              position={[-0.4, -9.73, 0.39]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Rectangle 2"
              geometry={nodes["Rectangle 2"].geometry}
              material={materials["Sneakers white"]}
              castShadow
              receiveShadow
              position={[-0.45, -20.06, -0.01]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group
            name="Group 4"
            position={[28.78, -238.18, 130.7]}
            rotation={[-0.09, 0, 0]}
            scale={[1.8, 1.66, 1.8]}
          >
            <mesh
              name="Torus 22"
              geometry={nodes["Torus 22"].geometry}
              material={materials["Torus 22 Material"]}
              castShadow
              receiveShadow
              position={[0.03, -7.05, 7.24]}
              rotation={[0, 0, -0.61]}
            />
            <mesh
              name="Torus2"
              geometry={nodes.Torus2.geometry}
              material={materials["Torus2 Material"]}
              castShadow
              receiveShadow
              position={[0, -5.6, 2.14]}
              rotation={[0, 0, -Math.PI / 4]}
            />
            <mesh
              name="Cube 45"
              geometry={nodes["Cube 45"].geometry}
              material={materials["Cube 45 Material"]}
              castShadow
              receiveShadow
              position={[0.03, -5.56, -27.01]}
              rotation={[Math.PI, 0, 0]}
              scale={0.9}
            />
            <mesh
              name="Cube 37"
              geometry={nodes["Cube 37"].geometry}
              material={materials["Sneakers white"]}
              castShadow
              receiveShadow
              position={[-0.5, -10.06, 16.62]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube 25"
              geometry={nodes["Cube 25"].geometry}
              material={materials["Sneakers blue"]}
              castShadow
              receiveShadow
              position={[-0.4, -9.73, 0.39]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Rectangle 21"
              geometry={nodes["Rectangle 21"].geometry}
              material={materials["Sneakers white"]}
              castShadow
              receiveShadow
              position={[-0.45, -20.06, -0.01]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <mesh
            name="Cube 111"
            geometry={nodes["Cube 111"].geometry}
            material={materials["Cube 111 Material"]}
            castShadow
            receiveShadow
            position={[24.35, 169.23, -43.04]}
            rotation={[-0.72, 0.22, 0.03]}
            scale={[1.48, 0.51, 0.46]}
          />
          <mesh
            name="pen"
            geometry={nodes.pen.geometry}
            material={materials["Plastic blue"]}
            castShadow
            receiveShadow
            position={[-51.59, 235.05, -45.23]}
            rotation={[0.48, -0.23, -0.21]}
          />
          <mesh
            name="裤子"
            geometry={nodes.裤子.geometry}
            material={materials["裤子 Material"]}
            castShadow
            receiveShadow
            position={[-3.67, 20.63, -73.2]}
          />
          <mesh
            name="Cube 17"
            geometry={nodes["Cube 17"].geometry}
            material={materials["Cube 17 Material"]}
            castShadow
            receiveShadow
            position={[-2.19, 116.88, -71.94]}
            scale={[1, 1, 0.95]}
          />
          <mesh
            name="body1"
            geometry={nodes.body1.geometry}
            material={materials["body1 Material"]}
            castShadow
            receiveShadow
            position={[-5.07, 112.17, -71.74]}
          />
        </group>
        <group
          name="head"
          position={[89.15, 217.54, -27.47]}
          rotation={[0.14, -0.53, -0.02]}
        >
          <mesh
            name="Cube 15"
            geometry={nodes["Cube 15"].geometry}
            material={materials["Cube 15 Material"]}
            castShadow
            receiveShadow
            position={[11.41, -1.05, 29.62]}
            rotation={[0, Math.PI / 9, 0]}
          />
          <mesh
            name="Cube 14"
            geometry={nodes["Cube 14"].geometry}
            material={materials["Cube 14 Material"]}
            castShadow
            receiveShadow
            position={[-21.35, -1.05, 28.72]}
            rotation={[0, -Math.PI / 9, 0]}
          />
          <mesh
            name="Cube 13"
            geometry={nodes["Cube 13"].geometry}
            material={materials.Eyebrows}
            castShadow
            receiveShadow
            position={[-21.98, 8.29, 29.17]}
            rotation={[-0.04, -0.41, -0.2]}
          />
          <mesh
            name="Cube 121"
            geometry={nodes["Cube 121"].geometry}
            material={materials.Eyebrows}
            castShadow
            receiveShadow
            position={[12.6, 4.37, 31.35]}
            rotation={[-0.1, 0.28, 0.2]}
          />
          <mesh
            name="Ellipse 2"
            geometry={nodes["Ellipse 2"].geometry}
            material={materials["Ellipse 2 Material"]}
            castShadow
            receiveShadow
            position={[-24.64, -21.51, 23.43]}
            rotation={[0.26, -0.58, 0]}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials["Ellipse Material"]}
            castShadow
            receiveShadow
            position={[16.55, -20.69, 24.79]}
            rotation={[0.26, 0.56, 0]}
          />
          <mesh
            name="Cube 91"
            geometry={nodes["Cube 91"].geometry}
            material={materials["Cube 91 Material"]}
            castShadow
            receiveShadow
            position={[0.99, -27.69, 27.99]}
            rotation={[0.16, -0.46, -2.93]}
            scale={[0.95, 1, 0.66]}
          />
          <mesh
            name="Cube 26"
            geometry={nodes["Cube 26"].geometry}
            material={materials["Cube 26 Material"]}
            castShadow
            receiveShadow
            position={[38.89, -9, -6.07]}
            scale={[-1, 1, 1]}
          />
          <mesh
            name="Cube2"
            geometry={nodes.Cube2.geometry}
            material={materials["Cube2 Material"]}
            castShadow
            receiveShadow
            position={[-46.02, -12.67, -6.07]}
          />
          <mesh
            name="hair"
            geometry={nodes.hair.geometry}
            material={materials["hair Material"]}
            castShadow
            receiveShadow
            position={[-3.26, 39.95, -32.33]}
            rotation={[-Math.PI / 6, 0, 0]}
            scale={[1.04, 1, 1]}
          />
          <mesh
            name="Sphere 21"
            geometry={nodes["Sphere 21"].geometry}
            material={materials["Sphere 21 Material"]}
            castShadow
            receiveShadow
            position={[-2.88, -8.51, -8.67]}
          />
        </group>
        <pointLight
          name="Point Light"
          cintensity={4}
          decay={20}
          distance={4222}
          color="#ada3fe"
          position={[316.98, 288.29, -187.75]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.75}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={2500}
          shadow-camera-left={-1200}
          shadow-camera-right={1200}
          shadow-camera-top={1200}
          shadow-camera-bottom={-1200}
          color="#fee5dd"
          position={[-533.7, 668.43, 796.96]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
          position={[0, 1, 0]}
        />
      </animated.group>
    </>
  );
}
